Begin:
  year: 2021
  month: 6
  day: 17
  hour: 0
  minute: 0
  second: 0
End:
  year: 2021
  month: 6
  day: 18
  hour: 9
  minute: 56
  second: 0
Action: current
MetricName: big_sequence
URL: 'http://172.20.3.120:9090'
Labels:
  - - 银行IC卡系统
    - 171.20.3.13
    - 银联商户
  - - 银行IC卡系统
    - 171.20.3.13
    - 银联POS机
  - - 银行IC卡系统
    - 171.20.3.13
    - ATM机
  - - 银行IC卡系统
    - 171.20.3.14
    - 银联商户
  - - 银行IC卡系统
    - 171.20.3.14
    - 银联POS机
  - - 银行IC卡系统
    - 171.20.3.14
    - ATM机
  - - 银行IC卡系统
    - 171.20.3.15
    - 银联商户
  - - 银行IC卡系统
    - 171.20.3.15
    - 银联POS机
  - - 银行IC卡系统
    - 171.20.3.15
    - ATM机
  - - ATM业务系统
    - 171.20.3.16
    - ATM机
  - - ATM业务系统
    - 171.20.3.17
    - ATM机
  - - ATM业务系统
    - 171.20.3.18
    - ATM机
  - - POS业务系统
    - 171.20.3.19
    - 银联POS机
  - - POS业务系统
    - 171.20.3.20
    - 银联POS机
